//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoraPlatform.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Elder
    {
        [DisplayName("身分證")]
        [Required(ErrorMessage = "身分證不可為空")]
        [RegularExpression("^[A-Z]{1}[1-2]{1}[0-9]{8}$", ErrorMessage = "身分證格式錯誤")]
        public string IdCard { get; set; }
        [DisplayName("姓名")]
        [Required(ErrorMessage = "姓名不可為空")]
        [RegularExpression("^[\u4e00-\u9fa5a-zA-Z0-9]+$", ErrorMessage = "姓名不可接受特殊字元")]
        public string Name { get; set; }
        [DisplayName("生日")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Required(ErrorMessage = "生日不可為空")]
        public System.DateTime Birthday { get; set; }
        [DisplayName("性別")]
        [Required(ErrorMessage = "性別不可為空")]
        public string Sex { get; set; }
        [DisplayName("親屬連絡電話")]
        [Required(ErrorMessage = "親屬連絡電話不可為空")]
        public string ContactPhone { get; set; }

        public Elder() { }

        public Elder(string name, string idcard, DateTime birthday, string sex, string contactphone)
        {
            Name = name;
            IdCard = idcard;
            Birthday = birthday;
            Sex = sex;
            ContactPhone = contactphone;
        }
    }
}
