//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoraPlatform.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class LoraData
    {
        public int Id { get; set; }
        [DisplayName("裝置Id")]
        [Required(ErrorMessage = "裝置Id不可為空")]
        public string DeviceId { get; set; }
        [DisplayName("緯度")]
        [Required(ErrorMessage = "緯度不可為空")]
        public string Latitude { get; set; }
        [DisplayName("精度")]
        [Required(ErrorMessage = "經度不可為空")]
        public string Longitude { get; set; }
        [DisplayName("時間")]
        [Required(ErrorMessage = "時間不可為空")]
        public System.DateTime Time { get; set; }
    }
}
