//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoraPlatform.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LoraPlatformEntities : DbContext
    {
        public LoraPlatformEntities()
            : base("name=LoraPlatformEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ConnectTable> ConnectTable { get; set; }
        public virtual DbSet<Device> Device { get; set; }
        public virtual DbSet<Elder> Elder { get; set; }
        public virtual DbSet<LoraData> LoraData { get; set; }
        public virtual DbSet<Members> Members { get; set; }
    }
}
